#include <SFML/Graphics.hpp>
const int HEIGHT_MAP = 29;
const int WIDTH_MAP = 56;

sf::String TileMap[HEIGHT_MAP] = {
	"00000000000000000000000000000000000000000000000000000000",
	"0                  ss        ss            ss          0",
	"0  ssssss  ssssss  ss  ssssssssssssssssss      s    s  0",
	"0  ss          ss  ss  ss              ss      ss  ss  0",
	"0  ss  ssssss  ss  s   ss  ssssss  ssssss  ss  ss  ss  0",
	"0  ss  ssf     ss      ssfhss  ssh         ss  ss      0",
	"0  ss  ss  s  fssssss  s   ss  ssssss  ssssss  sssss   0",
	"0  ss      ss      ss      ss              ss  ss      0",
	"0ssss      ssssssssssssss  ssssssssssssssssss  ss  s   0",
	"0      ss      ss  ss  ss          ss          ss  ss  0",
	"0  ssssssssssssss  ss  ssssss   s  ssfhssssssssssssss  0",
	"0              ss  ss      ss  ss  ss      ss  ss      0",
	"0ssssssssssss   s  s    s  ssssss  ssssss  s   ss  ssss0",
	"0          ss          ss              ss              0",
	"0  ssssss  ss  ssssss  ss       sssssssss  s   ssssss  0",
	"0          ss  ss  sshfss      ss          ss  ss      0",
	"0sss   ss  ss  ss  s   ss      ss  ssssssssssssss   sss0",
	"0  ss  ss      ss      ss      ss              ss      0",
	"0  ssssss  ssssssssss  ssssss  ssssssssssssss  s   ss  0",
	"0      ss      ss   f      ss              ss      ss  0",
	"0ssss  ssssssssss  ssssss  ssssss  ssssssssssssss   sss0",
	"0  ss  f           ss  ss     h     f  ss              0",
	"0  ss  ssssss  ssssss  ssssssssssssss  ss  ssssss   sss0",
	"0  ss  ss      ss      ss      h       ss  ss  ss  ss  0",
	"0  ss  ss  ssssss  sf  ssssss  ssssssssss  ss  ss  ss  0",
	"0      ss  ss      ss       f                  ss  ss  0",
	"0    ssss  ssssssssssssssssssssssssssssssssss  ss  ss  0",
	"0      ss    h                 ss              ss      0",
	"00000000000000000000000000000ww0000000000000000000000000",
};